Models/EmployeeContext.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace MVCbyPragim.Models
{
    public class EmployeeContext : DbContext
    {
        public DbSet<Employee> Employees { get; set; }
        public DbSet<Department> Department { get; set; }
    }

    public class Employee
    {
        public int EmployeeId { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public string City { get; set; }
        public int DepartmentId { get; set; }
    }
    public class Department
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

Controllers/DepartmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCbyPragim.Models;

namespace MVCbyPragim.Controllers
{
    public class DepartmentController : Controller
    {
        //
        // GET: /Department/

        public ActionResult Index()
        {
            EmployeeContext employeeContext = new EmployeeContext();
            List<Department> department = employeeContext.Department.ToList();
            return View(department);            
        }

    }
}

Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCbyPragim.Models;
using BusinessLayer;

namespace MVCbyPragim.Controllers
{
    public class EmployeeController : Controller
    {
        //
        // GET: /Employee/


        public ActionResult Index(int departmentId)
        {
            EmployeeContext employeeContext = new EmployeeContext();
            List<Employee> employee = employeeContext.Employees.Where(emp => emp.DepartmentId == departmentId).ToList();
            return View(employee);
        }
        [HttpGet]
        public ActionResult Details(int id)
        {
            EmployeeContext employeeContext = new EmployeeContext();
            //Employee employee = employeeContext.Employees.Single(emp => emp.EmployeeId == id);
            List<Employee> employee = employeeContext.Employees.Where(emp => emp.DepartmentId == id).ToList();
            return View(employee);
        }

        [HttpGet]
        public ActionResult DiplayDetails(int Id)
        {
            EmployeeBusinessLayer employeeBusinessLayer = new EmployeeBusinessLayer();
            //List<EmployeeBLL> employeeBLL = employeeBusinessLayer.Employee.Where(emp => emp.EmployeeId == Id).ToList();
            EmployeeBLL employeeBLL = employeeBusinessLayer.Employee.Single(id => id.EmployeeId == Id);

            return View(employeeBLL);
        }


        public ActionResult EmpDetails()
        {
            EmployeeBusinessLayer employeeBusinessLayer = new EmployeeBusinessLayer();
            IEnumerable<EmployeeBLL> employeeBLL = employeeBusinessLayer.Employee.ToList();
            return View(employeeBLL);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(EmployeeBLL employee)//(FormCollection formCollection)
        {
            //EmployeeBLL employee = new EmployeeBLL();
            //employee.Name = formCollection["Name"];
            //employee.Gender = formCollection["Gender"];
            //employee.City = formCollection["City"];
            //employee.DepartmentId = formCollection["DepartmentId"];

            TryUpdateModel(employee);
            if (ModelState.IsValid)
            {
                EmployeeBusinessLayer employeeBusinessLayer = new EmployeeBusinessLayer();
                employeeBusinessLayer.AddEmployee(employee);

                return RedirectToAction("EmpDetails");
            }

            //foreach (string key in formCollection.AllKeys)
            //{
            //    Response.Write("Key = " + key + " ");
            //    Response.Write(formCollection[key]);
            //    Response.Write("<br />");
            //}
            return View();
        }

        [HttpGet]
        public ActionResult Edit(int Id)
        {
            EmployeeBusinessLayer employeeBusinessLayer = new EmployeeBusinessLayer();
            EmployeeBLL employeeBLL = employeeBusinessLayer.Employee.Single(emp => emp.EmployeeId == Id);
            return View(employeeBLL);
        }

        [HttpPost]
        [ActionName("Edit")]
        public ActionResult Edit_Post(int Id)
        {
            EmployeeBusinessLayer employeeBusinessLayer = new EmployeeBusinessLayer();
            EmployeeBLL employee = employeeBusinessLayer.Employee.Single(id => id.EmployeeId == Id);
            UpdateModel(employee, new string[] { "City", "DepartmentId", "EmployeeId", "Gender" });
            if (ModelState.IsValid)
            {
                employeeBusinessLayer.UpdateEmployee(employee);
                return RedirectToAction("EmpDetails");
            }
            return View();

            //TryUpdateModel(empBLL);
            //if (ModelState.IsValid)
            //{
            //    EmployeeBusinessLayer employeeBusinessLayer = new EmployeeBusinessLayer();
            //    employeeBusinessLayer.UpdateEmployee(empBLL);
            //    return RedirectToAction("EmpDetails");
            //}
            //return View();
        }
        [HttpPost]
        public ActionResult DeleteRecord(int id)
        {
            if (ModelState.IsValid)
            {
                EmployeeBusinessLayer employeeBusinessLayer = new EmployeeBusinessLayer();
                employeeBusinessLayer.DeleteEmployeeRecord(id);
                return RedirectToAction("EmpDetails");

            }
            return View();
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCbyPragim.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/

        public ActionResult Index()
        {
            ViewBag.countries = new List<string>
            {
                "India",
                "US",
                "Australia",
                "Germany"
            };
            return View();
        }
    }
}

Views/Department/Index.cshtml
@*@model IEnumerable<MVCbyPragim.Models.Department>*@
@model IEnumerable<Department>
@using MVCbyPragim.Models;

@{
    Layout = null;
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Department Wise List</title>
</head>
<body>
    <b><u>Department Wise List</u></b>
    <ul>
        @foreach (Department department in @Model)
        {
            <li>
                @Html.ActionLink(department.Name, "Details", "Employee", new { Id = department.Id }, null)
            </li>
        }
    </ul>
</body>
</html>

Views/Employee/Create.cshtml
@model BusinessLayer.EmployeeBLL

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    <script src="~/Scripts/jquery-1.8.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)

        <fieldset>
            <legend>EmployeeBLL</legend>

            @*<div class="editor-label">
                    @Html.LabelFor(model => model.EmployeeId)
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.EmployeeId)
                    @Html.ValidationMessageFor(model => model.EmployeeId)
                </div>*@

            <div class="editor-label">
                @Html.LabelFor(model => model.Name)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Name)                
                @Html.ValidationMessageFor(model => model.Name)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.Gender)
            </div>
            <div class="editor-field">
                @Html.DropDownList("Gender", new List<SelectListItem>
           {
               new SelectListItem { Text="Male", Value="Male"},
               new SelectListItem { Text="Female", Value="Female"}
           }, "Select Gender")
                @Html.ValidationMessageFor(model => model.Gender)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.City)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.City)
                @Html.ValidationMessageFor(model => model.City)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.DepartmentId)
            </div>
            <div class="editor-field">
                @Html.DropDownList("DepartmentId", new List<SelectListItem>
                {
                    new SelectListItem{Text="1", Value="1"},
                    new SelectListItem{Text="2", Value="2"},
                    new SelectListItem{Text="3", Value="3"}
                }, "Select Department ID")
                @Html.ValidationMessageFor(model => model.DepartmentId)
            </div>
            <p>
                <input type="submit" value="Create" />
            </p>
        </fieldset>
    }
    <div>
        @Html.ActionLink("Back to List", "EmpDetails")
    </div>
</body>
</html>

Views/Employee/Details.cshtml
@model IEnumerable<MVCbyPragim.Models.Employee>
@using MVCbyPragim.Models;

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Employee Details</title>
</head>
<body>
    <b style="text-align:center"><u>Employee Names</u></b><br />
    @foreach (Employee emp in @Model)
    {
        @Html.ActionLink(emp.Name, "Index", "Employee", new { departmentId = emp.DepartmentId }, null)
        <br />

    }
    <div style="padding-top:20px; color:red; font-weight:800">
        @Html.ActionLink("Back to previous List", "Index", "Department");
    </div>
</body>
</html>

Views/Employee/DiplayDetails.cshtml
@*@model IEnumerable<BusinessLayer.EmployeeBLL>*@

@model BusinessLayer.EmployeeBLL


@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>DiplayDetails</title>
</head>
<body>
    <fieldset>
        <legend>EmployeeBLL</legend>

        <table border="1" class="display-label" style="height:200px; text-align:center">
            <tr>
                <td width="120px">
                    <b>@Html.DisplayNameFor(model => model.EmployeeId) : </b>
                </td>
                <td width="100px">
                    @Html.DisplayFor(model => model.EmployeeId)
                </td>
            </tr>
            <tr>
                <td>
                    <b>@Html.DisplayNameFor(model => model.Name) : </b>
                </td>
                <td>
                    @Html.DisplayFor(model => model.Name)
                </td>
            </tr>
            <tr>
                <td>
                    <b>@Html.DisplayNameFor(model => model.Gender) : </b>
                </td>
                <td>
                    @Html.DisplayFor(model => model.Gender)
                </td>
            </tr>
            <tr>
                <td>
                    <b>@Html.DisplayNameFor(model => model.City) : </b>
                </td>
                <td>
                    @Html.DisplayFor(model => model.City)
                </td>
            </tr>
            <tr>
                <td>
                    <b>@Html.DisplayNameFor(model => model.DepartmentId) : </b>
                </td>
                <td>
                    @Html.DisplayFor(model => model.DepartmentId)
                </td>
            </tr>
        </table>
    </fieldset>
    <p>
        @*@Html.ActionLink("Edit", "Edit", new { /* id=Model.PrimaryKey */ }) |*@
        @Html.ActionLink("Back to List", "EmpDetails")
    </p>
</body>
</html>

Views/Employee/Edit.cshtml
@model BusinessLayer.EmployeeBLL

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
    <style type="text/css">
        .redclass {
            color: red;
        }
    </style>
</head>
<body>
    <script src="~/Scripts/jquery-1.8.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)

        <fieldset style="width:250px">
            <legend><b><u>EmployeeBLL</u></b></legend>
            <table style="width:400px">
                <tr>
                    <td>
                        <b>@Html.LabelFor(model => model.EmployeeId)</b>
                        @*@Html.EditorFor(model => model.EmployeeId)*@
                    </td>
                    <td>
                        <b>:</b>  @Html.DisplayFor(model => model.EmployeeId)
                        @Html.ValidationMessageFor(model => model.EmployeeId, "", new { @class = "redclass" })
                    </td>
                </tr>
                <tr>
                    <td>
                        <b>@Html.LabelFor(model => model.Name)</b>
                        @*@Html.EditorFor(model => model.Name)*@
                    </td>
                    <td>
                        <b>:</b>  @Html.DisplayFor(model => model.Name)
                        @Html.HiddenFor(model => model.Name)
                        @Html.ValidationMessageFor(model => model.Name)
                    </td>
                </tr>
                <tr>
                    <td>
                        <b>@Html.LabelFor(model => model.Gender)</b>
                    </td>
                    <td>
                        <b>:</b>  @Html.DropDownList("Gender", new List<SelectListItem>
           {
               new SelectListItem { Text="Male", Value="Male"},
               new SelectListItem { Text="Female", Value="Female"}
           }, "Select Gender")
                        @Html.ValidationMessageFor(model => model.Gender)
                    </td>
                </tr>
                <tr>
                    <td>
                        <b>@Html.LabelFor(model => model.City)</b>
                    </td>
                    <td>
                        <b>:</b>  @Html.EditorFor(model => model.City)
                        @Html.ValidationMessageFor(model => model.City)
                    </td>
                </tr>
                <tr>
                    <td>
                        <b>@Html.LabelFor(model => model.DepartmentId)</b>
                    </td>
                    <td>
                        <b>:</b>  @Html.DropDownList("DepartmentId", new List<SelectListItem>
                {
                    new SelectListItem{Text="1", Value="1"},
                    new SelectListItem{Text="2", Value="2"},
                    new SelectListItem{Text="3", Value="3"}
                }, "Select ID")
                        @Html.ValidationMessageFor(model => model.DepartmentId)
                    </td>
                </tr>
                <tr>
                    <td></td>
                    <td style="padding-top:20px"><input type="submit" value="    Save    " /></td>
                </tr>
            </table>
        </fieldset>
    }
    <div>
        @Html.ActionLink("Back to List", "EmpDetails")
    </div>
</body>
</html>

Views/Employee/EmpDetails.cshtml
@model IEnumerable<BusinessLayer.EmployeeBLL>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>EmpDetails</title>
</head>
<body>
    <div style="font-family:'Segoe Marker'; color:green; text-align:center; padding-left:100px; padding-top:40px">
        <p style="background-color:lightgray; width:80px">
            @Html.ActionLink("Create New", "Create")
        </p>

        <table border="1" width:"50%">
            <tr style="color:violet; font-size:large">
                <th>
                    @Html.DisplayNameFor(model => model.EmployeeId)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Gender)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.City)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DepartmentId)
                </th>
                <th>Action</th>
            </tr>

            @foreach (var item in Model)
            {
                using (Html.BeginForm("DeleteRecord", "Employee", new { id = item.EmployeeId }))
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.EmployeeId)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Gender)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.City)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.DepartmentId)
                        </td>
                        <td style="color:red; width:200px">
                            @Html.ActionLink("Edit", "Edit", new { id = item.EmployeeId }) |
                            @Html.ActionLink("Details", "DiplayDetails", new { id = item.EmployeeId }) |
                            @*@Html.ActionLink("Delete", "DeleteRecord", new { id = item.EmployeeId })*@
                            <input type="submit" value="Delete" onclick="return confirm('Are you sure you want to delete record for ID = ' + @item.EmployeeId)" />
                        </td>
                    </tr>
                }
            }
        </table>
    </div>
</body>
</html>

Views/Employee/Index.cshtml
@model IEnumerable<MVCbyPragim.Models.Employee>


@{
    Layout = null;
}
@using MVCbyPragim.Models

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Employee List</title>
</head>
<body>
    <b style="text-align:center"><u>Employee List</u></b>

    @foreach (Employee emp in @Model)
    {
        <table style="border:2px solid; font-family:'Segoe UI'">
            <tr>
                <td>
                    <b>Employee Id :</b>
                </td>
                <td>
                    @emp.EmployeeId
                    @*@Html.ActionLink(emp.EmployeeId, "Details")*@
                </td>
            </tr>
            <tr>
                <td>
                    <b>Employee Name :</b>
                </td>
                <td>
                    @emp.Name
                    @*@Html.ActionLink(emp.Name, "Details")*@
                </td>
            </tr>
            <tr>
                <td>
                    <b>Employee Gender :</b>
                </td>
                <td>
                    @emp.Gender
                    @*@Html.ActionLink(emp.Gender, "Details")*@
                </td>
            </tr>
            <tr>
                <td>
                    <b>Employee City :</b>
                </td>
                <td>
                    @emp.City
                    @*@Html.ActionLink(emp.City, "Details")*@
                </td>
            </tr>
        </table>

        @*<li>
                @Html.ActionLink(employee.Name, "Details", new { id = employee.EmployeeId });
            </li>*@
    }

    @foreach (Employee e in @Model)
    {
        <div style="padding-top:20px; color:red; font-weight:800">

            @Html.ActionLink("Go Back to previous list", "Details", "Employee", new { id = e.DepartmentId }, null)
            
        </div>
    }
</body>
</html>

Views/Home/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Countries List</title>
</head>
<body>
    
        
    
</body>
</html>
@foreach (string strCountry in ViewBag.countries)
{
    <li>@strCountry</li>
}